/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-dim": "#40584f",
        "on-tertiary": "#edfbff",
        "on-background": "#2b3530",
        "on-error": "#fff7f6",
        "surface-container-high": "#e1eae4",
        "inverse-surface": "#0b0f0d",
        "error-container": "#fa746f",
        "on-secondary-fixed": "#2d443b",
        "on-primary-fixed-variant": "#466156",
        "inverse-on-surface": "#999e9a",
        "on-surface": "#2b3530",
        "on-primary-fixed": "#2a443b",
        "secondary-fixed-dim": "#c0dace",
        "primary-container": "#cbe9db",
        "on-error-container": "#6e0a12",
        "tertiary-dim": "#205a65",
        "surface-bright": "#f6faf6",
        "on-tertiary-fixed-variant": "#2c656f",
        "background": "#f6faf6",
        "outline-variant": "#aab4ae",
        "surface-container": "#e8f0ea",
        "inverse-primary": "#d7f5e7",
        "on-secondary-container": "#3f574d",
        "on-tertiary-container": "#205b65",
        "tertiary-fixed": "#b7effb",
        "secondary-fixed": "#cee9dc",
        "primary-fixed-dim": "#bedbce",
        "on-primary": "#e5fff2",
        "outline": "#737d78",
        "surface-container-highest": "#dae5de",
        "tertiary": "#2e6771",
        "secondary-container": "#cee9dc",
        "on-surface-variant": "#57615c",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#3d574d",
        "on-secondary": "#e5fff2",
        "secondary": "#4c645a",
        "primary-dim": "#3e594e",
        "primary": "#4a655a",
        "surface-dim": "#d2ddd6",
        "primary-fixed": "#cbe9db",
        "surface-tint": "#4a655a",
        "on-secondary-fixed-variant": "#496057",
        "error": "#a83836",
        "surface": "#f6faf6",
        "tertiary-container": "#b7effb",
        "error-dim": "#67040d",
        "surface-container-low": "#eff5f0",
        "surface-variant": "#dae5de",
        "on-tertiary-fixed": "#034852",
        "tertiary-fixed-dim": "#a9e0ec"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
    },
  },
  plugins: [],
}
